### ISSUE TITLE
这边全部配置安装完成了 ，打开域名或ip提示502 Bad Gateway

### ISSUE THREAD

**Issue by KingStrongers** [capricornxl/ad-password-self-service#11]
![image](https://user-images.githubusercontent.com/90755617/133420927-d358f3d7-baa2-450d-84d5-5c8c7b38f3f8.png)
不知道是nginx需要重新配置什么吗 我用的一键安装，安装过程未报错。请求协助  这是我的q 421381118
![image](https://user-images.githubusercontent.com/90755617/133421233-ee65370d-ff1a-468e-af58-b2da6e9f6646.png)

**Comment by KingStrongers** [comment]
![image](https://user-images.githubusercontent.com/90755617/133569911-6337a526-40fb-4cff-abf5-9ee0afc083e2.png)
![image](https://user-images.githubusercontent.com/90755617/133569979-a2ae5431-1a4d-44a1-85f2-c02b89c04c21.png)
![image](https://user-images.githubusercontent.com/90755617/133570081-e1edf315-c91f-4b06-8f4b-6036c1dba536.png)
![image](https://user-images.githubusercontent.com/90755617/133570131-06af1b8c-19a0-4990-a09c-de3c523dcaa3.png)
按照之前的解决办法还是不行   
![image](https://user-images.githubusercontent.com/90755617/133570231-a4a3c997-dfd6-48d9-9ede-ac1676f837dd.png)

**Comment by capricornxl** [comment]
你好，我加你QQ了。

**Comment by capricornxl** [comment]
己修复 ，代码己提交
