### ISSUE TITLE
搭建完后的问题

### ISSUE THREAD

**Issue by gzh540639382** [capricornxl/ad-password-self-service#14]
搭建完后，尝试修改密码，但提示用户名或密码不正确，用企业微信扫码。扫码后能检索到用户名，但输入新密码后提示报错，报错内容为（错误[LDAPOperationResult - LDAPOperationResult: 0000001F: SvcErr: DSID-031A12D2, problem 5003 (WILL_NOT_PERFORM), data 0 - None - None - None - None - None]，请与管理员联系.）

**Comment by jackwin886** [comment]
我搭建的也是提示用户名或密码不正确，兄弟，你这个企业微信扫码的是怎么配置，方便指导下吗

**Comment by gzh540639382** [comment]
就是直接按照他的教程，把几个码配置到配置文件里面就行了，但要填邮箱号，他好像检索的依据是邮箱？我感觉我配置的可能还是有点问题





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jackwin886 ***@***.***&gt;
发送时间: 2021年12月23日 17:00
收件人: capricornxl/ad-password-self-service ***@***.***&gt;
抄送: gzh540639382 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [capricornxl/ad-password-self-service] 搭建完后的问题 (Issue #14)





 
我搭建的也是提示用户名或密码不正确，兄弟，你这个企业微信扫码的是怎么配置，方便指导下吗

**Comment by jackwin886** [comment]
前端页面是不是也要改呢，可能是我企业微信没有开启授权登陆

**Comment by jackwin886** [comment]
好的，感谢，这个还的测试下是不是ldap配置哪里的问题，企业微信的改配置的值，前端就出来了

**Comment by gzh540639382** [comment]
有没有联系方式，一起探讨下

**Comment by capricornxl** [comment]
> 



> 



> 搭建完后，尝试修改密码，但提示用户名或密码不正确，用企业微信扫码。扫码后能检索到用户名，但输入新密码后提示报错，报错内容为（错误[LDAPOperationResult - LDAPOperationResult: 0000001F: SvcErr: DSID-031A12D2, problem 5003 (WILL_NOT_PERFORM), data 0 - None - None - None - None - None]，请与管理员联系.）

你的local_settings.py 中的
# AD域控的DOMAIN名，例如：abc
AD_DOMAIN = r'修改成自己的'

这里是什么样的？🤣🤣，这里估计有点误导，这个地方是域，这里写得是会引入到utils中ad_ops中做为登录到域使用。
比如我的域名是abc.com ，那么我使用AD登录时，应该是abc\xxxx 
上面的AD_DOMAIN应该是要写成abc，而不是abc.com

**Comment by capricornxl** [comment]
修改了domain这部分的提取逻辑，你们更新代码试下。

**Comment by gzh540639382** [comment]
收到，我现在就测试下！

**Comment by gzh540639382** [comment]
修改成功了，现在企业微信的就是提取邮箱前缀作为用户名去检索的对吧，必须完全匹配才能匹配到账号，是这个意思把

**Comment by capricornxl** [comment]
> 修改成功了，现在企业微信的就是提取邮箱前缀作为用户名去检索的对吧，必须完全匹配才能匹配到账号，是这个意思把

对的，目前的规则是这样的。

**Comment by gzh540639382** [comment]
好的，了解了，这个修改密码会刷新域控的重置密码待机时间吗，（预控规则三个月改一次密码）然后我看到还有解锁账号啥的是企业微信不能用的对吧

**Comment by capricornxl** [comment]
解锁账号企业微信可以用啊，这个就是企业微信或钉钉扫码之后，用户自己去解锁账号或重置密码，脱离需要求助管理员，减少管理员的工作量。
”刷新域控的重置密码待机时间“，修改密码应该是会触发AD的密码规则的。

**Comment by gzh540639382** [comment]
那就是用户账号被锁定的状态，才会有解锁账号的页面对吧

**Comment by capricornxl** [comment]
只要扫码验证通过了，就能解锁或重置密码，这个是用户自己去选择。
重置密码是必定会解锁一下账户的。

**Comment by gzh540639382** [comment]
看到了，还有一个很奇怪的问题，用ip访问页面挺正常的，然后企业微信扫码完后是默认跳转域名的网址，解析也做了，就是时不时会上不去

**Comment by capricornxl** [comment]
打开网页F12，查下跳转时网页的状态和报错。
