### ISSUE TITLE
自助修改密码系统对接飞书

### ISSUE THREAD

**Issue by Gcote0815** [capricornxl/ad-password-self-service#15]
想问下如何对接飞书

**Comment by Gcote0815** [comment]
通过你的库对接企业微信也出现了问题，提示 redirect_uri 与配置的授权完成回调域名不一致

**Comment by gzh540639382** [comment]
回调域名不一致好像是conf文件的最后一个域名不对

**Comment by capricornxl** [comment]
> 

因为我想偷懒，我就是用的conf里的那个域名。
如果你们实际情况不一致，就要手动改下。

**Comment by capricornxl** [comment]
> 想问下如何对接飞书

本来之前有时间想做的，结果一看飞书API或SDK都不全，文档也缺。就没弄了。
