### ISSUE TITLE
关于域名与IP跳转的问题

### ISSUE THREAD

**Issue by gzh540639382** [capricornxl/ad-password-self-service#16]
就比如我现在是用ip访问的网址，但微信扫码后默认会跳转到域名的网址上去，请问是否在哪边能更改，还有一个问题就是我发现在一键部署内设置了端口后，其实80端口和该端口都是能访问此页面的

**Comment by capricornxl** [comment]
> 就比如我现在是用ip访问的网址，但微信扫码后默认会跳转到域名的网址上去，请问是否在哪边能更改，还有一个问题就是我发现在一键部署内设置了端口后，其实80端口和该端口都是能访问此页面的

因为NGINX是在这台机器上，实际你走公网或域名就应该是通过80映射出去的了吧？

如果你现在是IP，就要改index.html里的东西，这里有个变量是从Django后端传过来的conf中的那个域名。
我不知道如果用IP，微信能不能支持。因为我看微信回调必须是HTTPS
