### ISSUE TITLE
建议可以添加到工作台

### ISSUE THREAD

**Issue by zyg0x0** [capricornxl/ad-password-self-service#18]
![1643018758(1)](https://user-images.githubusercontent.com/3190267/150762694-8ceaeccf-8f67-4fd2-9bef-5283976c8b10.jpg)

**Comment by capricornxl** [comment]
🤔，如果可以的话，可以自己试着做一下。
添加到工作台应该是更简单了，内部应用应该是直接能获取到当前用户的信息的，然后直接走重置或修改的逻辑。
换工作了，实在是太忙了，手头好几个事在弄。

**Comment by zyg0x0** [comment]
***@***.***

**Comment by zyg0x0** [comment]
***@***.***
