### ISSUE TITLE
密码复杂度限制

### ISSUE THREAD

**Issue by dashug** [capricornxl/ad-password-self-service#20]
看到现在对密码的复杂度是至少十位，必须要数字+大小写字母+符号，这个判断规则是写在哪儿的，想改成任意三种组合十位即可

**Comment by capricornxl** [comment]
> 
./resetpwd/form.py

`class CheckForm(c_forms.Form):
    new_password = c_fields.RegexField(
        '(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).{8,30}',
        # 密码必须同时包含大写、小写、数字和特殊字符其中三项且至少8位
        strip=True,
        min_length=8,
        max_length=30,
        error_messages={'required': '新密码不能为空.',
                        'invalid': '密码必须包含数字，字母、特殊字符',
                        'min_length': "密码长度不能小于8个字符",
                        'max_length': "密码长度不能大于30个字符"}
    )`
