### ISSUE TITLE
扫码成功后提示None格式化失败，企业微信获取不到邮箱了

### ISSUE THREAD

**Issue by Magicsz** [capricornxl/ad-password-self-service#22]
因为安全的问题，现在微信接口里获取不到邮箱地址，返回的user_info里email字段是空，提示"None格式化失败，注意：account用户账号是邮箱或DOMAIN\\username或username格式！"

**Comment by capricornxl** [comment]
![image](https://user-images.githubusercontent.com/40738379/202847137-402dd3bc-9477-4efd-bd03-c465c75dca04.png)

接口安全有变化了，这里估计代码逻辑要改。

**Comment by capricornxl** [comment]
哎，近期可能没空了，公司事太多。还没空看~
