### ISSUE TITLE
您好 请问一下我放到环境中自动安装 最后uwsgi 无法启动是什么原因

### ISSUE THREAD

**Issue by cjw0329** [capricornxl/ad-password-self-service#25]
![image](https://user-images.githubusercontent.com/121552979/209806518-994f76ba-f0fe-4550-9136-d0a9285bd3cd.png)

**Comment by capricornxl** [comment]
> ![image](https://user-images.githubusercontent.com/121552979/209806518-994f76ba-f0fe-4550-9136-d0a9285bd3cd.png)
知道原因了，自动部署脚本有点问题，没有处理Redis密码，这里我修复一下。

**Comment by capricornxl** [comment]
己修复，麻烦重新拉一次代码后，再试试吧。
