### ISSUE TITLE
部署完无法打开网页

### ISSUE THREAD

**Issue by mrggbond** [capricornxl/ad-password-self-service#3]
自动部署完成无报错，打开连接，浏览器提示504 Gateway Time-out，会是什么问题呢？

**Comment by capricornxl** [comment]
贴下你的NGINX配置我看看。

**Comment by mrggbond** [comment]
> 贴下你的NGINX配置我看看。
[root@xg nginx]# cat nginx.conf
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
=================
[root@xg conf.d]# cat pwdselfservice.conf 
server {
    listen  80;
    server_name xg.xxxx.com 10.10.23.131;

    location / {
        proxy_pass         http://10.10.23.131:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
        access_log off;
}

**Comment by mrggbond** [comment]
> 贴下你的NGINX配置我看看。
`[root@xg nginx]# cat nginx.conf 

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}`

`[root@xg conf.d]# cat pwdselfservice.conf 
server {
    listen  80;
    server_name xg.gzrb.com 10.10.23.131;

    location / {
        proxy_pass         http://10.10.23.131:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
        access_log off;
}`

**Comment by mrggbond** [comment]
> [root@xg nginx]# cat nginx.conf 
> 
> user  nginx;
> worker_processes  1;
> 
> error_log  /var/log/nginx/error.log warn;
> pid        /var/run/nginx.pid;
> 
> 
> events {
>     worker_connections  1024;
> }
> 
> 
> http {
>     include       /etc/nginx/mime.types;
>     default_type  application/octet-stream;
> 
>     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
>                       '$status $body_bytes_sent "$http_referer" '
>                       '"$http_user_agent" "$http_x_forwarded_for"';
> 
>     access_log  /var/log/nginx/access.log  main;
> 
>     sendfile        on;
>     #tcp_nopush     on;
> 
>     keepalive_timeout  65;
> 
>     #gzip  on;
> 
>     include /etc/nginx/conf.d/*.conf;
> }
> 
> [root@xg conf.d]# cat pwdselfservice.conf 
> server {
>     listen  80;
>     server_name xg.gzrb.com 10.10.23.131;
> 
>     location / {
>         proxy_pass         http://10.10.23.131:80;
>         proxy_set_header   Host              $host;
>         proxy_set_header   X-Real-IP         $remote_addr;
>         proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
>         proxy_set_header   X-Forwarded-Proto $scheme;
>     }
>         access_log off;
> }

**Comment by capricornxl** [comment]
http://10.10.23.131:80

**Comment by capricornxl** [comment]
http://10.10.23.131:80
这里proxy_pass的端口是Django项目运行的端口，你如果是和NGINX在同一台机，这里不能用80，因为NGINX默认就已经占用了80端口。
这一步配置的端口，是Django运行的端口，不要和NGINX一样。可以使用8000或8080这种。
![image](https://user-images.githubusercontent.com/40738379/98335624-47d3f100-2040-11eb-8a2c-da93924060a9.png)

**Comment by capricornxl** [comment]
可以手动修改uwsgi.ini配置文件中的端口，然后把proxy_pass         http://10.10.23.131:80;这一行中的80端口也修改掉，再重启uwsgi。

**Comment by capricornxl** [comment]
Issue先关了，有问题你再发Issue
