### ISSUE TITLE
自动脚本部署成功后网址502

### ISSUE THREAD

**Issue by woaili110** [capricornxl/ad-password-self-service#31]
系统：centos7.9
内核版本：3.10.0-1160.81.1.el7.x86_64
安装版本：1.0.7.6
现象：使用一键部署脚本安装成功后，打开域名502
请问我该如何修正该错误呢。谢谢

**Comment by capricornxl** [comment]
请直接使用master分支的代码，release 1.0.7.6 的auto-install脚本有点小BUG，我己修正。
然后release包我都清掉了，这个小项目每次生成release有点麻烦。后续请以master分支的为主，感谢。

**Comment by woaili110** [comment]
> 请直接使用master分支的代码，release 1.0.7.6 的auto-install脚本有点小BUG，我己修正。 然后release包我都清掉了，这个小项目每次生成release有点麻烦。后续请以master分支的为主，感谢。

好的，目前已经解决掉了，可以正常访问系统。感谢作者的付出。谢谢您

**Comment by yuzhifei** [comment]
系统：centos 8
内核版本：4.18.0-240.el8.x86_64
安装版本：ad-password-self-service-master 2月10日更新版本
现象：使用一键部署脚本安装成功后，打开域名502。
