### ISSUE TITLE
会报layui错误

### ISSUE THREAD

**Issue by lvzequan** [capricornxl/ad-password-self-service#33]
首次运行，没能正确加载layui.js文件，console报错Uncaught ReferenceError: layui is not defined，是由什么需要注意的吗？

**Comment by capricornxl** [comment]
看下static目录下的layui的目录结构。
F12，贴下Network那里的图。

**Comment by capricornxl** [comment]
你这是静态资源加载失败了。
看下uwsgi的日志，在项目目录log下有。
看看加载这些静态资源时有啥报错。

**Comment by capricornxl** [comment]
如果是这样，你需要将settings.py中的DEBUG开启，才能支持在python manage.py runserver使用静态资源。

**Comment by lvzequan** [comment]
> 如果是这样，你需要将settings.py中的DEBUG开启，才能支持在python manage.py runserver使用静态资源。

我把DEBUG开了，确实正常了，感谢。
