### ISSUE TITLE
请问重置密码能否添加禁止使用历史密码功能

### ISSUE THREAD

**Issue by h-yours** [capricornxl/ad-password-self-service#35]
考虑到安全性，重置AD密码能否添加禁止使用历史密码呢

**Comment by capricornxl** [comment]
如果从AD的角度来看，AD本身没这个限制。
但是说想实现的话，得自己加验证逻辑了，需要记录用户的之前多少次的密码（即多少次历史密码不能相同)，然后做对比。
这个得改代码了，还得弄数据库。

**Comment by chenbe1990** [comment]
AD上可以装Lithnet能达到这效果。
