### ISSUE TITLE
无法修改密码问题

### ISSUE THREAD

**Issue by wangxinhuan** [capricornxl/ad-password-self-service#5]
钉钉修改提示不符合复杂度，老密码修改提示老密码不对

**Comment by capricornxl** [comment]
账号状态呢？是否是锁定状态~
能不能确定老密码是正确的呀？

**Comment by wangxinhuan** [comment]
账号不是锁定状态，老密码正确的

**Comment by wangxinhuan** [comment]
还有发现DOMAIN\USERNAME  域账号格式不对，要是abc\\pwdadmin，必须是双斜杠

**Comment by capricornxl** [comment]
> 还有发现DOMAIN\USERNAME 域账号格式不对，要是abc\pwdadmin，必须是双斜杠

呃，这种格式的我没有用，具体的可能要看下ldap模块了。

**Comment by capricornxl** [comment]
> 账号不是锁定状态，老密码正确的

我已从上家公司离职了，现在的公司我没用这个平台了，回头我有时间的话部署一套测试下。
