### ISSUE TITLE
能否不用输入域名，只输入用户名？

### ISSUE THREAD

**Issue by gamerenzz** [capricornxl/ad-password-self-service#6]
比如默认输入的用户名为：domain\username或者邮箱地址

能否实现输入的用户名为：username  （不用加domain或邮箱地址）

这种情况是因为公司邮箱和域控是一个域名，而邮箱是外面租用那种，分开的

**Comment by capricornxl** [comment]
可以实现，那这个要改下代码。
那你们的邮箱的账号和域控账号名称是一样的吗？

**Comment by gamerenzz** [comment]
是一样的，请问要改的话，修改哪里的代码？

**Comment by capricornxl** [comment]
> 是一样的，请问要改的话，修改哪里的代码？

如果你有基础可以自行修改的话，就是代码里面判断账号状态的方法可能你都要重写一下。
类似ad_get_xxx_xxx_by_mail这种，就是带by_mail的，我都是通过邮箱来实现相关的状态返回。
ad_get_user_locked_status_by_mail
ad_get_user_status_by_mail
ad_modify_user_pwd_by_mail
等等这类.....
基本上都在ad.py这个里面，需要改成通过sAMAccountName属性的，我给出几个之前写过的。

def ad_ensure_user_by_sam(username):
    """
    通过sAMAccountName查询某个用户是否在AD中
    :param username:  除去@domain.com 的部分
    :return: True or False
    """
    conn = __ad_connect()
    base_dn = CONFIG.get('LDAP', 'SEARCH_BASE')
    condition = '(&(objectCategory=person)(objectClass=user)(sAMAccountName=%s))' % username
    attributes = ['sAMAccountName']
    return conn.search(base_dn, condition, attributes=attributes)


def ad_get_user_description_by_sam(username):
    conn = __ad_connect()
    base_dn = CONFIG.get('LDAP', 'SEARCH_BASE')
    conn.search(base_dn, '(&(objectclass=person)(sAMAccountName=' + username + '))', attributes=['description'])
    user_description = conn.entries[0]['description'].value
    conn.unbind()
    return user_description


def ad_get_user_displayname_by_sam(username):
    conn = __ad_connect()
    base_dn = CONFIG.get('LDAP', 'SEARCH_BASE')
    conn.search(base_dn, '(&(objectclass=person)(sAMAccountName=' + username + '))', attributes=['displayName'])
    user_displayname = conn.entries[0]['displayName'].value
    conn.unbind()
    return user_displayname


是当钉钉扫码验证通过之后，会提取当前钉钉账号的邮箱，这里的你可能也需要处理一下。

# 通过unionid在钉钉中拿到用户的邮箱
user_email = ding_get_userinfo_detail(ding_get_userid_by_unionid(unionid))['email']
# 如果邮箱在钉钉中能提取，则提交到前端绑定
if user_email:
    context = {
        'user_email': user_email,
    }
    return render(request, 'resetpwd.html', context)
这里你应该需要把邮箱的后缀去掉，提取出账号提前到前端。

**Comment by gamerenzz** [comment]
好的，谢谢了

**Comment by capricornxl** [comment]
> 好的，谢谢了

issue我先关了，后面有问题再交流。
有时间的话我把这玩意重写下，弄成兼容各种登录方式的。

**Comment by gamerenzz** [comment]
期待新版，感谢解答

**Comment by capricornxl** [comment]
> 期待新版，感谢解答

新版本己上线，己兼容和修复众多问题。

**Comment by gamerenzz** [comment]
> > 期待新版，感谢解答
> 
> 新版本己上线，己兼容和修复众多问题。

好的，谢谢了
